# Generated by Django 4.2.5 on 2023-10-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='has_seen',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created',
        ),
    ]
